name: builder-macos
on:
  push:
    branches:
      - master
      - develop
      - chore/ci/builder
  pull_request:
    branches:
      - master
      - develop
jobs:
  build-static:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: get nim
      run: |
        curl https://nim-lang.org/choosenim/init.sh -sSf | sh -s -- -y
    - name: build
      run: |
        export PATH=~/.nimble/bin:$PATH
        nim c --threads:on src/argon2_bind.nim
  build-dynamic:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: get nim
      run: |
        curl https://nim-lang.org/choosenim/init.sh -sSf | sh -s -- -y
    - name: build
      run: |
        export PATH=~/.nimble/bin:$PATH
        nim c -d:dynlink src/argon2_bind.nim
